<?php

return [
    'html',
    'css',
    'js',
    'php',
    'laravel',
    'mysql',
    'vuejs',
    'reactjs',
    'nodejs',
    'expressjs',
    'python',
    'django',
    "C++",
    "C#",
    "Customer Service",
    "C (Programming Language)",
    "Change Management",
    "Communication",
    "Coaching",
    "Customer Relationship Management (CRM)",
    "Contract Negotiation",
    "Construction",
     "Customer Satisfaction"
    , "Continuous Improvement"
    , "Cascading Style Sheets (CSS)"
    , "Community Outreach"
    , "Supply Chain Management"
    , "Cross-functional Team Leadership"
    , "Contract Management"
    , "Management Consulting"
    , "Construction Management"
    , "Adobe Creative Suite"
    , "Business Development"
    , "New Business Development"
    , "Data Analysis"
    , "Product Development"
    , "Software Development"
    , "Graphic Design"
    , "Digital Marketing"
    , "Leadership Development"
    , "Research and Development (R&D)"
    , "Data Entry"
    , "Organizational Development"
    , "Web Development"
    , "Databases"
    , "Web Design"
    , "Curriculum Development"
    , "Software Development Life Cycle (SDLC)"
    , "Staff Development"
    , "Oracle Database"
    , "Digital Media"
    , "Program Development"
    , "Microsoft Excel"
    , "English"
    , "Event Planning"
    , "Engineering"
    , "Event Management"
    , "Editing"
    , "E-Commerce"
    , "Entrepreneurship"
    , "Higher Education"
    , "E-Learning"
    , "Employee Relations"
    , "Real Estate"
    , "Microsoft Office"
    , "Project Engineering"
    , "Energy"
    , "Search Engine Optimization (SEO)"
    , "Employee Training"
    , "Email Marketing"
    , "Enterprise Resource Planning (ERP)"
    , "Project Management"
    , "Microsoft PowerPoint"
    , "Strategic Planning"
    , "Public Speaking"
    , "Adobe Photoshop"
    , "Project Planning"
    , "Public Relations"
    , "Program Management"
    , "Manufacturing Process Improvement"
    , "Business Planning"
    , "Business Process Improvement"
    , "Problem Solving"
    , "Photography"
    , "SAP Products"
    , "Python (Programming Language)"
    , "Product Management"
    , "Public Policy"
    , "F#"
    , "Financial Analysis"
    , "Finance"
    , "Financial Reporting"
    , "Fundraising"
    , "Forecasting"
    , "Financial Accounting"
    , "Food and Beverage Operations"
    , "Facebook"
    , "French"
    , "Corporate Finance"
    , "Financial Modeling"
    , "Fashion"
    , "Financial Services"
    , ".NET Framework"
    , "Leadership"
    , "G++"
    , "Government"
    , "Oil and Gas"
    , "Git"
    , "Gas"
    , "Grant Writing"
    , "Lead Generation"
    , "Google Analytics"
    , "Fast-Moving Consumer Goods (FMCG)"
    , "Corporate Governance"
    , "General Ledgers"
    , "Sales"
    , "Graphics"
    , "Research Skills"
    , "Requirements Gathering"
    , "Good Manufacturing Practice (GMP)"
    , "German"
    , "HTML"
    , "Healthcare"
    , "Human Resources (HR)"
    , "Hospitals"
    , "Healthcare Management"
    , "Hospitality Industry"
    , "HTML5"
    , "Hotel Management"
    , "Hospitality Management"
    , "Computer Hardware"
    , "Healthcare Information Technology (HIT)"
    , "Mental Health"
    , "Public Health"
    , "U.S. Health Insurance Portability and Accountability Act (HIPAA)"
    , "HR Consulting"
    , "Inventory Management"
    , "Adobe Illustrator"
    , "IT Integration"
    , "Business Intelligence (BI)"
    , "Adobe InDesign"
    , "Insurance"
    , "ITIL"
    , "Investments"
    , "Interviewing"
    , "Information Technology"
    , "Internal Controls"
    , "Interpersonal Skills"
    , "IT Service Management"
    , "Java"
    , "JavaScript"
    , "jQuery"
    , "J#"
    , "Journalism"
    , "Jakarta EE"
    , "Jira"
    , "Node.js"
    , "Core Java"
    , "JSON"
    , "React.js"
    , "JavaServer Pages (JSP)"
    , "Criminal Justice"
    , "Online Journalism"
    , "Jenkins"
    , "Journal Entries (Accounting)"
    , "Joint Ventures"
    , "Joomla!"
    , "Kaizen"
    , "K-12 Education"
    , "Key Account Development"
    , "Kanban"
    , "Key Performance Indicators"
    , "401(k) Retirement Savings Plans"
    , "Accounting"
    , "Knowledge Management"
    , "Project Management Body of Knowledge (PMBOK)"
    , "10-Key Typing"
    , "Product Knowledge"
    , "KPI Reporting"
    , "Kubernetes"
    , "KYC Verification"
    , "Keynote"
    , "Keyword Research"
    , "Knitwear"
    , "Team Leadership"
    , "Logistics Management"
    , "Linux"
    , "Lean Manufacturing"
    , "P&L Management"
    , "Legal Research"
    , "Management"
    , "Legal Writing"
    , "Litigation"
    , "Educational Leadership"
    , "Logo Design"
    , "Corporate Law"
    , "Loans"
    , "Microsoft Word"
    , "Social Media"
    , "Marketing"
    , "Marketing Strategy"
    , "Sales Management"
    , "Time Management"
    , "Team Management"
    , "Account Management"
    , "Social Media Marketing"
    , "Operations Management"
    , "N+"
    , "Negotiation"
    , "Nonprofit Organizations"
    , "Networking"
    , "Nursing"
    , "Network Administration"
    , "ASP.NET"
    , "Network Security"
    , "New Media"
    , "Newsletters"
    , "Nutrition"
    , "Critical Care Nursing"
    , "Network Design"
    , "Microsoft Outlook"
    , "Sales Operations"
    , "Online Marketing"
    , "Online Advertising"
    , "Office Administration"
    , "Organization Skills"
    , "Operating Systems"
    , "Quality Assurance"
    , "Quality Management"
    , "Qualitative Research"
    , "QuickBooks"
    , "Quality Control"
    , "Quality System"
    , "Quantitative Research"
    , "Quality Auditing"
    , "Micro Focus Quality Center"
    , "Software Quality Assurance"
    , "Q#"
    , "Analytical Skills"
    , "SQL"
    , "Advanced Product Quality Planning (APQP)"
    , "Quantity Surveying"
    , "Language Integrated Query (LINQ)"
    , "R&R"
    , "Retail"
    , "Recruiting"
    , "Risk Management"
    , "Market Research"
    , "Requirements Analysis"
    , "R (Programming Language)"
    , "Clinical Research"
    , "A++"
    , "AutoCAD"
    , "Business Analysis"
    , "Advertising"
    , "Mergers & Acquisitions (M&A)"
    , "Software as a Service (SaaS)"
    , "Agile Methodologies"
    , "Auditing"
    , "Business Strategy"
    , "Team Building"
    , "Budgeting"
    , "Banking"
    , "Business-to-Business (B2B)"
    , "Blogging"
    , "Business Process"
    , "Brand Development"
    , "Small Business"
    , "Brand Management"
    , "Alpine JS"
    , "Livewire"
    , "Tailwind css"
    , "Inertia JS"
    , "TDD"
    , "PEST PHP"
    , "Wordpress"
    , "Drupal"
    , "Symfony"
    , "Codignator"
    , "Flask"
    , "Pinia"
    , "JEST"
    , "Mysql"
    , "Oracal"
    , "MS Sql"
    , "Node"
    , "Angular JS"
    , "Ruby On Rails"
    , "Bootstrap"
    , "PHPmyadmin"
    , "Cloud Computing"
    , "AWS"
    , "Valet"
    ,"REST API",
    "GraphQL",

    ];

